// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CmNavbar: typeof import('./src/components/cm-navbar/cm-navbar.vue')['default']
    CmPlaylistCard: typeof import('./src/components/cm-playlist-card/cm-playlist-card.vue')['default']
    CmSkeleton: typeof import('./src/components/cm-skeleton/cm-skeleton.vue')['default']
    ElTree: typeof import('element-plus/es')['ElTree']
    PlaylistCard: typeof import('./src/components/cm-playlist-card/playlist-card.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TypeNav: typeof import('./src/components/cm-navbar/type-nav.vue')['default']
  }
}

export {}
