// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CmAlbumCard: typeof import('./src/components/cm-album-card/cm-album-card.vue')['default']
    CmComment: typeof import('./src/components/cm-comment/cm-comment.vue')['default']
    CmError: typeof import('./src/components/cm-error/cm-error.vue')['default']
    CmLoading: typeof import('./src/components/cm-loading/cm-loading.vue')['default']
    CmMvCard: typeof import('./src/components/cm-mv-card/cm-mv-card.vue')['default']
    CmNavbar: typeof import('./src/components/cm-navbar/cm-navbar.vue')['default']
    CmPlaylistCard: typeof import('./src/components/cm-playlist-card/cm-playlist-card.vue')['default']
    CmSkeleton: typeof import('./src/components/cm-skeleton/cm-skeleton.vue')['default']
    CmTable: typeof import('./src/components/cm-table/cm-table.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
